In [121]:
import os
from bs4 import BeautifulSoup
import json

In [122]:
class Scraper:
    def __init__(self,temp_path:str,config_path:str):
        self.temp_path = temp_path
        if not os.path.exists(self.temp_path):
            raise ValueError(f'Temp Path does not exist. I was given {self.temp_path}')
        self.config_path = config.path
        if not os.path.exists(self.config_path):
            raise ValueError(f'ConfigPath does not exist')
    def _load_config_params():
        with

In [123]:
soup_page:list[BeautifulSoup] = [] 
for i in os.listdir('../temp'):
    full_path = os.path.join('../temp',i)
    print(i)
    with open(full_path,'r') as file:
        content = file.read()
    soup_page.append(BeautifulSoup(content))

15.html
1.html
2.html
3.html
17.html
5.html
13.html
9.html
11.html
20.html
8.html
10.html
6.html
14.html
12.html
4.html
16.html
18.html
19.html
7.html

In [124]:
css_selectors = {
    'ad':'a.dIkIJy',
    'title':'h3.hDGITe',
    'additional_info':'span.daYHkI',
    'car_info': 'div.WbYSG',
    'type_of_seller':'span.kWavwo:nth-of-type(1)',
    'location':'span.kWavwo[aria-label]',
    'price':'span.czQcuf',
}

In [125]:
soup_page[0].select_one('a.dIkIJy').get('href')

'https://www.willhaben.at/iad/gebrauchtwagen/d/auto/skoda-citigo-iv-5-tuerer-673320609/'

In [126]:
res = []
for page in soup_page:
    all_ads = page.select(css_selectors['ad'])
    print(len(all_ads))
    for car in all_ads:
        car_data = {}
        car_data['link'] = car.get('href')
        for name,selector in css_selectors.items():
            if name == 'ad':
                continue
            else:
                try:
                    car_data[name] = car.select_one(selector).text
                except:
                    car_data[name] = 'N/A'
        res.append(car_data)

66
30
50
50
66
5
5
50
5
66
50
50
50
5
5
50
66
66
66
50

In [127]:
import pandas as pd

In [128]:
df = pd.DataFrame(res)

In [129]:
df

,link,title,additional_info,car_info,type_of_seller,location,price
0,https://www.willhaben.at/iad/gebrauchtwagen/d/...,Skoda Citigo iV 5-Türer,"Elektro, Automatik, gültiges Pickerl, Gewährle...",2020 EZ16.450 km83 PS (61 kW),Händler,4950 Altheim,€ 17.900
1,https://www.willhaben.at/iad/gebrauchtwagen/d/...,BMW 5er-Reihe 530d,"Diesel, Automatik",2005 EZ308.000 km218 PS (160 kW),Privat,3371 Neumarkt an der Ybbs,€ 3.000
2,https://www.willhaben.at/iad/gebrauchtwagen/d/...,Maserati Quattroporte Maserati Quattroporte AB...,"gültiges Pickerl, Gewährleistung",2006 EZ80.305 km401 PS (295 kW),Q-Car Company,2103 Langenzersdorf,€ 24.500
3,https://www.willhaben.at/iad/gebrauchtwagen/d/...,"Hyundai i10 1,0 Comfort NUR NOCH DIESE WOCHE","Benzin, Schaltgetriebe, gültiges Pickerl",2014 EZ95.000 km65 PS (48 kW),Privat,4210 Gallneukirchen,€ 6.000
4,https://www.willhaben.at/iad/gebrauchtwagen/d/...,"Skoda Fabia Ambiente 1,2 TSI","Benzin, Schaltgetriebe, gültiges Pickerl, Gewä...",2010 EZ111.000 km86 PS (63 kW),Beinten Cars,9800 Spittal an der Drau,€ 5.700
...,...,...,...,...,...,...,...
846,https://www.willhaben.at/iad/gebrauchtwagen/d/...,"Toyota RAV4 2,5 Hybrid Active AWD","Hybrid Elektro/Benzin, Automatik, Gewährleistung",2019 EZ79.200 km178 PS (131 kW),Auto Bacher GmbH,6060 Hall in Tirol,€ 33.900
847,https://www.willhaben.at/iad/gebrauchtwagen/d/...,"Skoda Kodiaq 1,4 TSI ACT 4x4 Ambition","Benzin, Schaltgetriebe, gültiges Pickerl, Gewä...",2017 EZ78.200 km150 PS (110 kW),Autohaus Kirschner GmbH,7123 Mönchhof,€ 24.990
848,https://www.willhaben.at/iad/gebrauchtwagen/d/...,VW Touran 2.0 TDI Highline R-Line LED AHK SKY ...,"Diesel, Schaltgetriebe, Gewährleistung",2018 EZ67.988 km150 PS (110 kW),Onlinecars Vertriebs GmbH,9220 Lind ob Velden,€ 27.890
849,https://www.willhaben.at/iad/gebrauchtwagen/d/...,Ford Ka,"Benzin, Schaltgetriebe, gültiges Pickerl",2006 EZ214.000 km60 PS (44 kW),Privat,"1160 Wien, 16. Bezirk, Ottakring",€ 600
850,https://www.willhaben.at/iad/gebrauchtwagen/d/...,Renault Captur TCe 100 PF Intens,"Benzin, Schaltgetriebe, Gewährleistung",2020 EZ15.832 km101 PS (74 kW),Sonnleitner GmbH,4040 Linz,€ 17.900

In [ ]:
df